package internal

//go:generate go run ../cmd/generate -input ../commands.json -output generated_commands.go

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"sort"
	"strings"
	"text/template"
)

// CommandDefinition maps a single entry in commands.json.
type CommandDefinition struct {
	CommandName  string
	Fields       []FieldDefinition
	InjectLogger bool
}

// FieldDefinition describes one struct field in a command.
type FieldDefinition struct {
	Name   string
	Type   string
	TagKey string
	TagVal string
	Desc   string
}

const structTemplate = `
type {{.CommandName}}Command struct {
{{- range .Fields}}
	{{.Name}} {{.Type}} ` + "`" + `{{.TagKey}}:"{{.TagVal}}" desc:"{{.Desc}}"` + "`" + `
{{- end}}
{{- if .InjectLogger}}
	Logger *Logger ` + "`" + `di:"inject"` + "`" + `
{{- end}}
}
`

const registryTemplate = `
var commandRegistry = map[string]reflect.Type{
{{- range .}}
	"{{.Key}}": reflect.TypeFor[*{{.CommandName}}Command](),
{{- end}}
}
`

const fileHeader = `// Code generated by stargo command generator. DO NOT EDIT.

package internal

import "reflect"
`

type registryEntry struct {
	Key         string
	CommandName string
}

// GenerateCommands reads command definitions from inputPath and writes
// generated Go source to outputPath.
func GenerateCommands(inputPath, outputPath string) error {
	defs, err := readDefinitions(inputPath)
	if err != nil {
		return fmt.Errorf("generator: read definitions: %w", err)
	}

	if err := validateDefinitions(defs); err != nil {
		return fmt.Errorf("generator: validate: %w", err)
	}

	sort.Slice(defs, func(i, j int) bool {
		return defs[i].CommandName < defs[j].CommandName
	})

	structs, err := renderStructs(defs)
	if err != nil {
		return fmt.Errorf("generator: render structs: %w", err)
	}

	registry, err := renderRegistry(defs)
	if err != nil {
		return fmt.Errorf("generator: render registry: %w", err)
	}

	src := fileHeader + structs + registry

	formatted, err := format.Source([]byte(src))
	if err != nil {
		return fmt.Errorf("generator: format source: %w", err)
	}

	if err := writeGeneratedFile(outputPath, formatted); err != nil {
		return fmt.Errorf("generator: write file: %w", err)
	}

	return nil
}

func readDefinitions(path string) ([]CommandDefinition, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read file %s: %w", path, err)
	}

	val, err := UnmarshalFromJSON(data, reflect.TypeFor[[]CommandDefinition]())
	if err != nil {
		return nil, fmt.Errorf("unmarshal: %w", err)
	}

	defs, ok := val.Interface().([]CommandDefinition)
	if !ok {
		return nil, fmt.Errorf("unexpected decoded type %T", val.Interface())
	}

	return defs, nil
}

func validateDefinitions(defs []CommandDefinition) error {
	allowed := map[string]bool{"cli": true, "pos": true}

	for _, def := range defs {
		if def.CommandName == "" {
			return fmt.Errorf("command has empty CommandName")
		}

		for _, f := range def.Fields {
			if f.Name == "" || f.Type == "" {
				return fmt.Errorf("command %s: field missing Name or Type", def.CommandName)
			}

			if !allowed[f.TagKey] {
				return fmt.Errorf("command %s: field %s has unsupported TagKey %q", def.CommandName, f.Name, f.TagKey)
			}
		}
	}

	return nil
}

func renderStructs(defs []CommandDefinition) (string, error) {
	tmpl, err := template.New("struct").Parse(structTemplate)
	if err != nil {
		return "", fmt.Errorf("parse struct template: %w", err)
	}

	var buf bytes.Buffer
	for _, def := range defs {
		if err := tmpl.Execute(&buf, def); err != nil {
			return "", fmt.Errorf("execute struct template for %s: %w", def.CommandName, err)
		}
	}

	return buf.String(), nil
}

func renderRegistry(defs []CommandDefinition) (string, error) {
	entries := make([]registryEntry, len(defs))
	for i, def := range defs {
		entries[i] = registryEntry{
			Key:         strings.ToLower(def.CommandName),
			CommandName: def.CommandName,
		}
	}

	tmpl, err := template.New("registry").Parse(registryTemplate)
	if err != nil {
		return "", fmt.Errorf("parse registry template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, entries); err != nil {
		return "", fmt.Errorf("execute registry template: %w", err)
	}

	return buf.String(), nil
}

func writeGeneratedFile(path string, content []byte) error {
	tmp := path + ".tmp"

	if err := os.WriteFile(tmp, content, 0o644); err != nil {
		return fmt.Errorf("write temp file: %w", err)
	}

	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("rename to target: %w", err)
	}

	return nil
}
