// Code generated by stargo command generator. DO NOT EDIT.

package internal

import "reflect"

type CancelCommand struct {
	ID     string  `pos:"1" desc:"ID of the order to cancel"`
	Logger *Logger `di:"inject"`
}

type LoadCommand struct {
	Name      string  `pos:"1" desc:"Name of the cargo"`
	Weight    int     `cli:"weight" desc:"Weight of the cargo in kg"`
	Hazardous bool    `cli:"hazardous" desc:"Is the cargo dangerous?"`
	Logger    *Logger `di:"inject"`
}

var commandRegistry = map[string]reflect.Type{
	"cancel": reflect.TypeFor[*CancelCommand](),
	"load":   reflect.TypeFor[*LoadCommand](),
}
